chore: Override minimum MacOS SDK version, b=no-bug, c=workflows

diff --git a/.github/workflows/macos-release-build.yml b/.github/workflows/macos-release-build.yml
--- a/.github/workflows/macos-release-build.yml
+++ b/.github/workflows/macos-release-build.yml
@@ -122,9 +122,12 @@ jobs:
 
       - name: Bootstrap
         run: |
+          cd engine
           export SURFER_PLATFORM="darwin"
           export PATH="$(python3 -m site --user-base)/bin":$PATH
-          npm run bootstrap
+          # Always exist with 0, even if bootstrap fails
+          ./mach --no-interactive bootstrap --application-choice browser --exclude macos-sdk || true
+          cd ..
 
       - name: Build language packs
         run: sh scripts/download-language-packs.sh
